#if !defined(AFX_MAP_H__7E62D0BE_8925_4801_811E_69C7533CDDDC__INCLUDED_)
#define AFX_MAP_H__7E62D0BE_8925_4801_811E_69C7533CDDDC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoLayers;
class CMoRectangle;
class CMoTrackingLayer;
class CMoPoint;
class CMoEllipse;
class CMoLine;
class CMoPolygon;
class CMoGeoDatasets;
class CMoDataConnection;
class CMoGeoDataset;
class CMoMapLayer;
class CMoRecordset;
class CMoFields;
class CMoField;
class CMoPoints;
class CMoSymbol;
class CMoValueMapRenderer;
class CMoStrings;
class CMoStatistics;
class CMoClassBreaksRenderer;
class CMoDotDensityRenderer;
class CMoLabelRenderer;
class CMoGeoEvent;
class CMoImageLayer;
class CMoTable;
class CMoTextSymbol;
class CMoTableDesc;
class CMoAddressLocation;
class CMoPlaceLocator;
class CMoParts;
class CMoProjection;
class CMoProjCoordSys;
class CMoGeoCoordSys;
class CMoUnit;
class CMoDatum;
class CMoSpheroid;
class CMoPrimeMeridian;
class CMoGeoTransformation;
class CMoStandardizer;
class CMoGeocoder;
class CMoZRenderer;
class CMoGroupRenderer;
class CMoChartRenderer;
class CMoLabelPlacer;
class CMoEventRenderer;

/////////////////////////////////////////////////////////////////////////////
// CMap1 wrapper class

class CMap1 : public CWnd
{
protected:
	   DECLARE_DYNCREATE(CMap1)
	   
public:
	    CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9bd6a64b, 0xce75, 0x11d1, { 0xaf, 0x4, 0x20, 0x4c, 0x4f, 0x4f, 0x50, 0x20 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CMoLayers GetLayers();
	void SetLayers(LPDISPATCH);
	CMoRectangle GetExtent();
	void SetExtent(LPDISPATCH);
	CMoRectangle GetFullExtent();
	void SetFullExtent(LPDISPATCH);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetBorderStyle();
	void SetBorderStyle(short);
	BOOL GetScrollBars();
	void SetScrollBars(BOOL);
	long GetCancelAction();
	void SetCancelAction(long);
	CMoTrackingLayer GetTrackingLayer();
	void SetTrackingLayer(LPDISPATCH);
	long GetRefreshCount();
	void SetRefreshCount(long);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	short GetAppearance();
	void SetAppearance(short);
	double GetMinWidth();
	void SetMinWidth(double);
	long GetMousePointer();
	void SetMousePointer(long);
	BOOL GetFullRedrawOnPan();
	void SetFullRedrawOnPan(BOOL);
	VARIANT GetCoordinateSystem();
	void SetCoordinateSystem(const VARIANT&);
	long GetMaxFileBuffer();
	void SetMaxFileBuffer(long);
	long GetWindowMode();
	void SetWindowMode(long);
	double GetRotationAngle();
	void SetRotationAngle(double);
	LPDISPATCH GetVisibleRegion();
	void SetVisibleRegion(LPDISPATCH);
	long GetGeometryEnvironment();
	void SetGeometryEnvironment(long);
	long GetDisplayUnit();
	void SetDisplayUnit(long);
	long GetTrackingLayerDrawing();
	void SetTrackingLayerDrawing(long);

// Operations
public:
	void AboutBox();
	void Pan();
	CMoPoint ToMapPoint(float X, float Y);
	void FlashShape(LPDISPATCH shape, short nTimes);
	void Refresh();
	void DrawShape(LPDISPATCH shape, LPDISPATCH Symbol);
	void DrawText(LPCTSTR text, LPDISPATCH shape, LPDISPATCH Symbol);
	CMoEllipse TrackCircle();
	CMoLine TrackLine();
	CMoRectangle TrackRectangle();
	void FromMapPoint(LPDISPATCH Point, float* X, float* Y);
	double ToMapDistance(float distance);
	float FromMapDistance(double distance);
	CMoPolygon TrackPolygon();
	void OutputMap(long hDC);
	void PrintMap(LPCTSTR docName, LPCTSTR outputFile, BOOL landscapeOrientation);
	void ExportMap(long exportType, LPCTSTR outputFile, double scaleFactor);
	void CopyMap(double scaleFactor);
	void CenterAt(double X, double Y);
	void RefreshLayer(short index, const VARIANT& rect);
	void ExportMap2(long exportType, LPCTSTR outputFile, double scaleFactor, const VARIANT& useSourceDepth);
	void OutputMap2(long hDC, long X, long Y, long Width, long Height, const VARIANT& DrawFlags);
	void RefreshRect(LPDISPATCH rect);
	void EnableTIFFLZW(LPCTSTR licenseCode);
	void EnableGIF(LPCTSTR licenseCode);
	void EnableStreetMap(LPCTSTR licenseCode);
	void ExportMapToJpeg(LPCTSTR outputFile, long percentQuality, BOOL isProgressive, double scaleFactor, long scaleSymbology);
	void ExportMap3(long formatType, const VARIANT& formatData, double scaleFactor, long scaleSymbology, long exportDepth, long palette);
	void OutputMap3(long hDC, long X, long Y, long Width, long Height, const VARIANT& DrawFlags, double scaleFactor, long scaleSymbology, const VARIANT& outputExtent);
	void ExportMapToJpeg2(LPCTSTR outputFile, long percentQuality, BOOL isProgressive, double scaleFactor, long scaleSymbology, const VARIANT& exportExtent);
	void ExportMap4(long formatType, const VARIANT& formatData, double scaleFactor, long scaleSymbology, long exportDepth, long palette, const VARIANT& exportExtent);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MAP_H__7E62D0BE_8925_4801_811E_69C7533CDDDC__INCLUDED_)
