// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "moaddresslocation.h"

// Dispatch interfaces referenced by this interface
#include "mopoint.h"


/////////////////////////////////////////////////////////////////////////////
// CMoAddressLocation properties

CMoPoint CMoAddressLocation::GetLocation()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return CMoPoint(pDispatch);
}

void CMoAddressLocation::SetLocation(LPDISPATCH propVal)
{
	SetProperty(0x1, VT_DISPATCH, propVal);
}

short CMoAddressLocation::GetMatchScore()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CMoAddressLocation::SetMatchScore(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

long CMoAddressLocation::GetStreetSide()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CMoAddressLocation::SetStreetSide(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CMoAddressLocation operations
