#if !defined(AFX_MODATACONNECTION_H__228371BF_99DD_4355_9728_D583A2ED979A__INCLUDED_)
#define AFX_MODATACONNECTION_H__228371BF_99DD_4355_9728_D583A2ED979A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoGeoDataset;
class CMoStrings;

/////////////////////////////////////////////////////////////////////////////
// CMoDataConnection wrapper class

class CMoDataConnection : public COleDispatchDriver
{
public:
	CMoDataConnection() {}		// Calls COleDispatchDriver default constructor
	CMoDataConnection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoDataConnection(const CMoDataConnection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetConnected();
	void SetConnected(BOOL);
	CString GetDatabase();
	void SetDatabase(LPCTSTR);
	CString GetServer();
	void SetServer(LPCTSTR);
	CString GetUser();
	void SetUser(LPCTSTR);
	CString GetPassword();
	void SetPassword(LPCTSTR);
	LPDISPATCH GetGeoDatasets();
	void SetGeoDatasets(LPDISPATCH);
	long GetConnection();
	void SetConnection(long);
	long GetConnectError();
	void SetConnectError(long);
	long GetExtendedError();
	void SetExtendedError(long);
	CString GetExtendedErrorString();
	void SetExtendedErrorString(LPCTSTR);

// Operations
public:
	BOOL Connect();
	void Disconnect();
	CMoGeoDataset FindGeoDataset(LPCTSTR Name);
	CMoGeoDataset AddGeoDataset(LPCTSTR Name, long shapeType, LPDISPATCH TableDesc, const VARIANT& HasZ, const VARIANT& HasMeasure);
	BOOL DeleteGeoDataset(LPCTSTR Name);
	LPDISPATCH FindCoordinateSystem(LPCTSTR Name);
	void ClearConnectError();
	LPDISPATCH FindArcInfoCoordinateSystem(LPCTSTR Name);
	CMoStrings ReturnVersions();
	CString GetVersion();
	void SetVersion(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MODATACONNECTION_H__228371BF_99DD_4355_9728_D583A2ED979A__INCLUDED_)
