#if !defined(AFX_MODOTDENSITYRENDERER_H__1FA43413_4CF1_41D9_9276_ADA9C5C71EDC__INCLUDED_)
#define AFX_MODOTDENSITYRENDERER_H__1FA43413_4CF1_41D9_9276_ADA9C5C71EDC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoDotDensityRenderer wrapper class

class CMoDotDensityRenderer : public COleDispatchDriver
{
public:
	CMoDotDensityRenderer() {}		// Calls COleDispatchDriver default constructor
	CMoDotDensityRenderer(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoDotDensityRenderer(const CMoDotDensityRenderer& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetField();
	void SetField(LPCTSTR);
	double GetDotValue();
	void SetDotValue(double);
	short GetDotSize();
	void SetDotSize(short);
	unsigned long GetDotColor();
	void SetDotColor(unsigned long);
	BOOL GetDrawBackground();
	void SetDrawBackground(BOOL);
	CString GetTag();
	void SetTag(LPCTSTR);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MODOTDENSITYRENDERER_H__1FA43413_4CF1_41D9_9276_ADA9C5C71EDC__INCLUDED_)
