#if !defined(AFX_MOEVENTRENDERER_H__D0377789_90B4_4F68_BCD7_4155AA2831AE__INCLUDED_)
#define AFX_MOEVENTRENDERER_H__D0377789_90B4_4F68_BCD7_4155AA2831AE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoSymbol;
class CMoTable;
class CMoRectangle;

/////////////////////////////////////////////////////////////////////////////
// CMoEventRenderer wrapper class

class CMoEventRenderer : public COleDispatchDriver
{
public:
	CMoEventRenderer() {}		// Calls COleDispatchDriver default constructor
	CMoEventRenderer(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoEventRenderer(const CMoEventRenderer& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetTag();
	void SetTag(LPCTSTR);
	BOOL GetUseDefault();
	void SetUseDefault(BOOL);
	CMoSymbol GetDefaultSymbol();
	void SetDefaultSymbol(LPDISPATCH);
	long GetSymbolType();
	void SetSymbolType(long);
	short GetValueCount();
	void SetValueCount(short);
	CString GetFeatureRouteIDField();
	void SetFeatureRouteIDField(LPCTSTR);
	CString GetEventRouteIDField();
	void SetEventRouteIDField(LPCTSTR);
	CString GetStartMeasureField();
	void SetStartMeasureField(LPCTSTR);
	CString GetEndMeasureField();
	void SetEndMeasureField(LPCTSTR);
	CString GetSymbolField();
	void SetSymbolField(LPCTSTR);
	BOOL GetDrawBackground();
	void SetDrawBackground(BOOL);
	CMoTable GetEventTable();
	void SetEventTable(LPDISPATCH);
	BOOL GetIndexEvents();
	void SetIndexEvents(BOOL);
	CMoRectangle GetIndexExtent();
	void SetIndexExtent(LPDISPATCH);

// Operations
public:
	CMoSymbol GetSymbol(short index);
	CString GetValue(short index);
	void SetValue(short index, LPCTSTR lpszNewValue);
	BOOL InvalidateIndex(LPCTSTR key);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOEVENTRENDERER_H__D0377789_90B4_4F68_BCD7_4155AA2831AE__INCLUDED_)
