#if !defined(AFX_MOGEOCOORDSYS_H__7D1C9CAD_14B7_4B45_AA58_192638B75358__INCLUDED_)
#define AFX_MOGEOCOORDSYS_H__7D1C9CAD_14B7_4B45_AA58_192638B75358__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoDatum;
class CMoUnit;
class CMoPrimeMeridian;

/////////////////////////////////////////////////////////////////////////////
// CMoGeoCoordSys wrapper class

class CMoGeoCoordSys : public COleDispatchDriver
{
public:
	CMoGeoCoordSys() {}		// Calls COleDispatchDriver default constructor
	CMoGeoCoordSys(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoGeoCoordSys(const CMoGeoCoordSys& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetType();
	void SetType(long);
	CString GetName();
	void SetName(LPCTSTR);
	CMoDatum GetDatum();
	void SetDatum(LPDISPATCH);
	CMoUnit GetUnit();
	void SetUnit(LPDISPATCH);
	CMoPrimeMeridian GetPrimeMeridian();
	void SetPrimeMeridian(LPDISPATCH);
	BOOL GetIsProjected();
	void SetIsProjected(BOOL);

// Operations
public:
	LPDISPATCH Transform(LPDISPATCH FromCoordSys, LPDISPATCH FromShape, const VARIANT& DensificationTolerance, const VARIANT& GeoTransformation);
	void Export(LPCTSTR OutName);
	CString ReturnDescription();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOGEOCOORDSYS_H__7D1C9CAD_14B7_4B45_AA58_192638B75358__INCLUDED_)
