// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mogrouprenderer.h"


/////////////////////////////////////////////////////////////////////////////
// CMoGroupRenderer properties

short CMoGroupRenderer::GetCount()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CMoGroupRenderer::SetCount(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

BOOL CMoGroupRenderer::GetDrawBackground()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CMoGroupRenderer::SetDrawBackground(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

CString CMoGroupRenderer::GetTag()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CMoGroupRenderer::SetTag(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CMoGroupRenderer operations

LPDISPATCH CMoGroupRenderer::GetRenderer(short index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, parms,
		index);
	return result;
}

void CMoGroupRenderer::SetRefRenderer(short index, LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_DISPATCH;
	InvokeHelper(0x5, DISPATCH_PROPERTYPUTREF, VT_EMPTY, NULL, parms,
		 index, newValue);
}

short CMoGroupRenderer::Add(LPDISPATCH Renderer)
{
	short result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		Renderer);
	return result;
}

void CMoGroupRenderer::Remove(short index)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 index);
}
