#if !defined(AFX_MOIMAGELAYER_H__0116C2BD_15FB_4224_BC65_BF21228F6D74__INCLUDED_)
#define AFX_MOIMAGELAYER_H__0116C2BD_15FB_4224_BC65_BF21228F6D74__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoRectangle;

/////////////////////////////////////////////////////////////////////////////
// CMoImageLayer wrapper class

class CMoImageLayer : public COleDispatchDriver
{
public:
	CMoImageLayer() {}		// Calls COleDispatchDriver default constructor
	CMoImageLayer(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoImageLayer(const CMoImageLayer& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetVisible();
	void SetVisible(BOOL);
	CString GetName();
	void SetName(LPCTSTR);
	CMoRectangle GetExtent();
	void SetExtent(LPDISPATCH);
	CString GetFile();
	void SetFile(LPCTSTR);
	long GetLayerType();
	void SetLayerType(long);
	CString GetTag();
	void SetTag(LPCTSTR);
	BOOL GetValid();
	void SetValid(BOOL);
	BOOL GetUpdateWhileDrawing();
	void SetUpdateWhileDrawing(BOOL);
	BOOL GetTransparent();
	void SetTransparent(BOOL);
	unsigned long GetTransparentColor();
	void SetTransparentColor(unsigned long);

// Operations
public:
	void OpenCatalog(LPDISPATCH pTable, LPCTSTR ImageDirPath, long OpenOptions);
	long GetColumns();
	long GetRows();
	CMoRectangle GetClipExtent();
	void SetClipExtent(LPDISPATCH newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOIMAGELAYER_H__0116C2BD_15FB_4224_BC65_BF21228F6D74__INCLUDED_)
