#if !defined(AFX_MOLAYERS_H__7D38CDAF_9AA0_49C9_A53E_BD82E04DA81A__INCLUDED_)
#define AFX_MOLAYERS_H__7D38CDAF_9AA0_49C9_A53E_BD82E04DA81A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoLayers wrapper class

class CMoLayers : public COleDispatchDriver
{
public:
	CMoLayers() {}		// Calls COleDispatchDriver default constructor
	CMoLayers(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoLayers(const CMoLayers& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	LPDISPATCH Item(const VARIANT& index);
	BOOL Add(LPDISPATCH layer);
	void Remove(short index);
	void Clear();
	void MoveTo(short fromIndex, short toIndex);
	void MoveToTop(short index);
	void MoveToBottom(short index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOLAYERS_H__7D38CDAF_9AA0_49C9_A53E_BD82E04DA81A__INCLUDED_)
