#if !defined(AFX_MOLINE_H__B95614AA_0726_44B9_BF66_134E18C0798A__INCLUDED_)
#define AFX_MOLINE_H__B95614AA_0726_44B9_BF66_134E18C0798A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoRectangle;
class CMoParts;
class CMoPoints;

/////////////////////////////////////////////////////////////////////////////
// CMoLine wrapper class

class CMoLine : public COleDispatchDriver
{
public:
	CMoLine() {}		// Calls COleDispatchDriver default constructor
	CMoLine(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoLine(const CMoLine& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CMoRectangle GetExtent();
	void SetExtent(LPDISPATCH);
	CMoParts GetParts();
	void SetParts(LPDISPATCH);
	double GetLength();
	void SetLength(double);
	long GetShapeType();
	void SetShapeType(long);
	BOOL GetIsFullyMeasured();
	void SetIsFullyMeasured(BOOL);

// Operations
public:
	void Offset(double deltaX, double deltaY);
	double DistanceTo(LPDISPATCH shape);
	CMoPoints GetCrossings(LPDISPATCH shape);
	CMoPoints ReturnPointEvents(double Measure);
	CMoLine ReturnLineEvent(double start, double end);
	double ReturnMeasure(LPDISPATCH location);
	void UpdateMeasures();
	void SetMeasures(double start, double end);
	void SetMeasuresAsLength();
	void OffsetMeasures(double Offset);
	void MultiplyMeasures(double factor);
	LPDISPATCH Union(LPDISPATCH anotherLine, const VARIANT& Extent);
	LPDISPATCH Xor(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Difference(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Intersect(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Buffer(double distance, const VARIANT& Extent);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOLINE_H__B95614AA_0726_44B9_BF66_134E18C0798A__INCLUDED_)
