#if !defined(AFX_MOPARTS_H__EB8F7BA9_21BB_4424_ADED_B777ED2C37A2__INCLUDED_)
#define AFX_MOPARTS_H__EB8F7BA9_21BB_4424_ADED_B777ED2C37A2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoParts wrapper class

class CMoParts : public COleDispatchDriver
{
public:
	CMoParts() {}		// Calls COleDispatchDriver default constructor
	CMoParts(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoParts(const CMoParts& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	void Add(LPDISPATCH Points);
	void Set(short index, LPDISPATCH Points);
	void Remove(short index);
	void Insert(short index, LPDISPATCH Points);
	LPDISPATCH Item(const VARIANT& Item);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOPARTS_H__EB8F7BA9_21BB_4424_ADED_B777ED2C37A2__INCLUDED_)
