#if !defined(AFX_MOPLACELOCATOR_H__193F5CC9_ABD2_4721_85FB_575DA282D4FB__INCLUDED_)
#define AFX_MOPLACELOCATOR_H__193F5CC9_ABD2_4721_85FB_575DA282D4FB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoGeoDataset;
class CMoPoints;
class CMoStrings;

/////////////////////////////////////////////////////////////////////////////
// CMoPlaceLocator wrapper class

class CMoPlaceLocator : public COleDispatchDriver
{
public:
	CMoPlaceLocator() {}		// Calls COleDispatchDriver default constructor
	CMoPlaceLocator(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoPlaceLocator(const CMoPlaceLocator& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetIndexed();
	void SetIndexed(BOOL);
	CMoGeoDataset GetPlaceNameTable();
	void SetPlaceNameTable(LPDISPATCH);

// Operations
public:
	BOOL BuildIndex(LPCTSTR Field, BOOL force);
	CMoPoints Locate(LPCTSTR placeName);
	CMoStrings FindApproximateMatches(LPCTSTR placeName);
	CMoStrings FindAllPlaceNames(LPCTSTR prefix);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOPLACELOCATOR_H__193F5CC9_ABD2_4721_85FB_575DA282D4FB__INCLUDED_)
