#if !defined(AFX_MOPOINT_H__802FDC57_B877_47B0_AB0B_0ACFBD619A0B__INCLUDED_)
#define AFX_MOPOINT_H__802FDC57_B877_47B0_AB0B_0ACFBD619A0B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoPoints;

/////////////////////////////////////////////////////////////////////////////
// CMoPoint wrapper class

class CMoPoint : public COleDispatchDriver
{
public:
	CMoPoint() {}		// Calls COleDispatchDriver default constructor
	CMoPoint(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoPoint(const CMoPoint& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	double GetY();
	void SetY(double);
	double GetX();
	void SetX(double);
	double GetZ();
	void SetZ(double);
	double GetMeasure();
	void SetMeasure(double);
	long GetShapeType();
	void SetShapeType(long);

// Operations
public:
	double DistanceTo(LPDISPATCH shape);
	double DistanceToSegment(LPDISPATCH point1, LPDISPATCH point2);
	CMoPoints GetCrossings(LPDISPATCH shape);
	LPDISPATCH Union(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Xor(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Difference(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Intersect(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Buffer(double distance, const VARIANT& Extent);
	void Set(double X, double Y, double Z, double Measure);
	void Get(double* X, double* Y, double* Z, double* Measure);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOPOINT_H__802FDC57_B877_47B0_AB0B_0ACFBD619A0B__INCLUDED_)
