#if !defined(AFX_MOPOINTS_H__16E7742A_A601_4DCD_A6DE_28743486115E__INCLUDED_)
#define AFX_MOPOINTS_H__16E7742A_A601_4DCD_A6DE_28743486115E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoRectangle;
class CMoPoint;

/////////////////////////////////////////////////////////////////////////////
// CMoPoints wrapper class

class CMoPoints : public COleDispatchDriver
{
public:
	CMoPoints() {}		// Calls COleDispatchDriver default constructor
	CMoPoints(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoPoints(const CMoPoints& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);
	long GetShapeType();
	void SetShapeType(long);
	CMoRectangle GetExtent();
	void SetExtent(LPDISPATCH);

// Operations
public:
	CMoPoint Item(const VARIANT& Item);
	void Add(LPDISPATCH Point);
	void Set(long index, LPDISPATCH Point);
	void Remove(long index);
	void Insert(long index, LPDISPATCH Point);
	void Reverse();
	void Offset(double deltaX, double deltaY);
	double DistanceTo(LPDISPATCH shape);
	CMoPoints GetCrossings(LPDISPATCH shape);
	LPDISPATCH Union(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Xor(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Difference(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Intersect(LPDISPATCH anotherShape, const VARIANT& Extent);
	LPDISPATCH Buffer(double distance, const VARIANT& Extent);
	// method 'SetPoints' not emitted because of invalid return type or parameter type
	// method 'GetPoints' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOPOINTS_H__16E7742A_A601_4DCD_A6DE_28743486115E__INCLUDED_)
