// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "moprimemeridian.h"


/////////////////////////////////////////////////////////////////////////////
// CMoPrimeMeridian properties

long CMoPrimeMeridian::GetType()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CMoPrimeMeridian::SetType(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

CString CMoPrimeMeridian::GetName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CMoPrimeMeridian::SetName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

double CMoPrimeMeridian::GetLongitude()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CMoPrimeMeridian::SetLongitude(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CMoPrimeMeridian operations
