#if !defined(AFX_MOPROJECTION_H__FEDC262A_D88A_4105_818D_EE90D7D71F99__INCLUDED_)
#define AFX_MOPROJECTION_H__FEDC262A_D88A_4105_818D_EE90D7D71F99__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoProjection wrapper class

class CMoProjection : public COleDispatchDriver
{
public:
	CMoProjection() {}		// Calls COleDispatchDriver default constructor
	CMoProjection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoProjection(const CMoProjection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetType();
	void SetType(long);
	CString GetName();
	void SetName(LPCTSTR);
	LPUNKNOWN GetCustom();
	void SetCustom(LPUNKNOWN);
	BOOL GetIsCustom();
	void SetIsCustom(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOPROJECTION_H__FEDC262A_D88A_4105_818D_EE90D7D71F99__INCLUDED_)
