// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mospheroid.h"


/////////////////////////////////////////////////////////////////////////////
// CMoSpheroid properties

long CMoSpheroid::GetType()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CMoSpheroid::SetType(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

double CMoSpheroid::GetAxis()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CMoSpheroid::SetAxis(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

double CMoSpheroid::GetFlattening()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CMoSpheroid::SetFlattening(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

CString CMoSpheroid::GetName()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CMoSpheroid::SetName(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CMoSpheroid operations
