#if !defined(AFX_MOSPHEROID_H__E4445181_A602_461C_9DAF_C09753E934BA__INCLUDED_)
#define AFX_MOSPHEROID_H__E4445181_A602_461C_9DAF_C09753E934BA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoSpheroid wrapper class

class CMoSpheroid : public COleDispatchDriver
{
public:
	CMoSpheroid() {}		// Calls COleDispatchDriver default constructor
	CMoSpheroid(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoSpheroid(const CMoSpheroid& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetType();
	void SetType(long);
	double GetAxis();
	void SetAxis(double);
	double GetFlattening();
	void SetFlattening(double);
	CString GetName();
	void SetName(LPCTSTR);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOSPHEROID_H__E4445181_A602_461C_9DAF_C09753E934BA__INCLUDED_)
