#if !defined(AFX_MOSTATISTICS_H__A3408733_3F07_4D0C_A394_4B4905C01763__INCLUDED_)
#define AFX_MOSTATISTICS_H__A3408733_3F07_4D0C_A394_4B4905C01763__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoStatistics wrapper class

class CMoStatistics : public COleDispatchDriver
{
public:
	CMoStatistics() {}		// Calls COleDispatchDriver default constructor
	CMoStatistics(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoStatistics(const CMoStatistics& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	double GetMax();
	void SetMax(double);
	double GetMin();
	void SetMin(double);
	double GetMean();
	void SetMean(double);
	double GetStdDev();
	void SetStdDev(double);
	double GetSum();
	void SetSum(double);
	long GetCount();
	void SetCount(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOSTATISTICS_H__A3408733_3F07_4D0C_A394_4B4905C01763__INCLUDED_)
