#if !defined(AFX_MOSYMBOL_H__51180916_8754_4E10_A5C2_45F360ECC477__INCLUDED_)
#define AFX_MOSYMBOL_H__51180916_8754_4E10_A5C2_45F360ECC477__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CMoSymbol wrapper class

class CMoSymbol : public COleDispatchDriver
{
public:
	CMoSymbol() {}		// Calls COleDispatchDriver default constructor
	CMoSymbol(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoSymbol(const CMoSymbol& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetSize();
	void SetSize(short);
	short GetStyle();
	void SetStyle(short);
	unsigned long GetColor();
	void SetColor(unsigned long);
	short GetCharacterIndex();
	void SetCharacterIndex(short);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	unsigned long GetOutlineColor();
	void SetOutlineColor(unsigned long);
	long GetSymbolType();
	void SetSymbolType(long);
	BOOL GetOutline();
	void SetOutline(BOOL);
	BOOL GetCenterOnAscent();
	void SetCenterOnAscent(BOOL);
	LPUNKNOWN GetCustom();
	void SetCustom(LPUNKNOWN);
	double GetRotation();
	void SetRotation(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOSYMBOL_H__51180916_8754_4E10_A5C2_45F360ECC477__INCLUDED_)
