#if !defined(AFX_MOTABLE_H__7F6357F7_575A_45B6_BCA8_6DD2C908BD7D__INCLUDED_)
#define AFX_MOTABLE_H__7F6357F7_575A_45B6_BCA8_6DD2C908BD7D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoRecordset;

/////////////////////////////////////////////////////////////////////////////
// CMoTable wrapper class

class CMoTable : public COleDispatchDriver
{
public:
	CMoTable() {}		// Calls COleDispatchDriver default constructor
	CMoTable(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoTable(const CMoTable& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetUser();
	void SetUser(LPCTSTR);
	CString GetPassword();
	void SetPassword(LPCTSTR);
	CString GetDatabase();
	void SetDatabase(LPCTSTR);
	CString GetName();
	void SetName(LPCTSTR);
	CMoRecordset GetRecords();
	void SetRecords(LPDISPATCH);
	CString GetServer();
	void SetServer(LPCTSTR);

// Operations
public:
	CMoRecordset SearchExpression(LPCTSTR expression);
	CString GetVersion();
	void SetVersion(LPCTSTR lpszNewValue);
	LPDISPATCH GetCommand();
	void SetRefCommand(LPDISPATCH newValue);
	long GetMaxCachedRelateRecords();
	void SetMaxCachedRelateRecords(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOTABLE_H__7F6357F7_575A_45B6_BCA8_6DD2C908BD7D__INCLUDED_)
