#if !defined(AFX_MOTRACKINGLAYER_H__F9340409_C16E_4F8C_8A02_99B22E346B5A__INCLUDED_)
#define AFX_MOTRACKINGLAYER_H__F9340409_C16E_4F8C_8A02_99B22E346B5A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoSymbol;
class CMoGeoEvent;

/////////////////////////////////////////////////////////////////////////////
// CMoTrackingLayer wrapper class

class CMoTrackingLayer : public COleDispatchDriver
{
public:
	CMoTrackingLayer() {}		// Calls COleDispatchDriver default constructor
	CMoTrackingLayer(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoTrackingLayer(const CMoTrackingLayer& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetEventCount();
	void SetEventCount(long);
	long GetSymbolCount();
	void SetSymbolCount(long);
	BOOL GetVisible();
	void SetVisible(BOOL);

// Operations
public:
	CMoSymbol GetSymbol(long index);
	CMoGeoEvent GetEvent(long index);
	void RemoveEvent(long index);
	CMoGeoEvent AddEvent(LPDISPATCH shape, long SymbolIndex);
	void ClearEvents();
	void Refresh(BOOL erase, const VARIANT& rect);
	CMoGeoEvent FindEvent(LPCTSTR Tag);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOTRACKINGLAYER_H__F9340409_C16E_4F8C_8A02_99B22E346B5A__INCLUDED_)
